# Configuração Senior - API Golden Raspberry Awards
# Demonstra configurações externalizadas e práticas avançadas

spring:
  application:
    name: golden-raspberry-awards-api
  
  profiles:
    active: senior
  
  # Configurações do banco H2
  datasource:
    url: jdbc:h2:mem:moviedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # Configurações JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  
  # Console H2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# Configurações customizadas da aplicação
movieapi:
  csv:
    delimiter: ";"
    encoding: "UTF-8"
    skip-first-line: true
    batch-size: 500
  
  calculation:
    include-non-consecutive: false
    max-results: 50
    enable-caching: true
    cache-expiration-minutes: 30
  
  performance:
    enable-metrics: true
    enable-slow-query-logging: true
    slow-query-threshold-ms: 500
    thread-pool-size: 5

# Configurações do servidor
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always

# Configurações de logging
logging:
  level:
    com.texoit.airton.movieapi: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: logs/movieapi.log
    max-size: 10MB
    max-history: 30

# Configurações de management/actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  
  endpoint:
    health:
      show-details: always
      
  metrics:
    export:
      prometheus:
        enabled: true

# Configurações de validação
validation:
  enabled: true
  fail-fast: false

# Configurações de documentação
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    
  show-actuator: true

# Configurações de cache
spring.cache:
  type: simple
  cache-names:
    - producer-intervals
    - movie-data 